### PR TITLE
Implement fixes and update to Python 3.8

### PR DESCRIPTION
**Pull request by CasperWA**
Implement changes and fixes from CasperWA/voila-optimade-client#419.

### CODE REVIEW

**Review by unkcpz — APPROVED** [review]
Looks all good. @CasperWA thanks!

**Comment by CasperWA** [comment]
Just looking at building it at well for dev-dokku. I essentially have the "herokuish_build" CI job to check that the build is good - but it's always good to double check with an actual push. I normally wouldn't do that until a PR has been merged though...

**Comment by CasperWA** [comment]
Concerning the build error, I think it's fine. It's a timing issue since `jupyter` does not exist on the system at the time of wheel building. In theory it should still run this part during the subsequent installation, and `jupyter` should be installed at that point. As a point of proof is that the template is visible in the deployment :)

**Comment by unkcpz** [comment]
> I essentially have the "herokuish_build" CI job to check that the build is good - but it's always good to double check with an actual push. I normally wouldn't do that until a PR has been merged though

I see. So this repo will automatically do it? I guess that's why sometimes the tool down and then somehow works again?

**Comment by CasperWA** [comment]
> > I essentially have the "herokuish_build" CI job to check that the build is good - but it's always good to double check with an actual push. I normally wouldn't do that until a PR has been merged though
> 
> I see. So this repo will automatically do it? I guess that's why sometimes the tool down and then somehow works again?

This repo will automatically build - this is a CI job (see the checks or Actions tab as well as the `.github/workflows` folder in the repository.
Originally, this would also push to `matcloud.xyz` on each push to `master`, however, due to the new access restrictions this fails. So one needs to do it manually after merging a PR.

Once everything is good on `matcloud.xyz` one can push to `materialscloud.io` (production), which should always be done manually after testing the app a bit.

**Comment by CasperWA** [comment]
I will push to production now

**Comment by unkcpz** [comment]
Thanks a lot for all the explanation. It is now all clear to me how everything works together. 🥳

**Pull request merged**
