### PR TITLE
Improve performance by using kernel pool

### PR DESCRIPTION
**Pull request by unkcpz**
As described at https://github.com/materialscloud-org/tools-optimade-client/issues/107, in the sense, this improves the performance of opening a new voila app.

@dou-du Do you also use this for other dokku apps? Is this really useful?

### CODE REVIEW

**Comment by dou-du** [comment]
> As described at #107, in the sense, this improves the performance of opening a new voila app.
> 
> @dou-du Do you also use this for other dokku apps? Is this really useful?

I have never tried this before. I will make some tests for OSSCAR apps.

**Review by CasperWA — APPROVED** [review]
Looks fine to me, maybe after merging this can be deployed to `dev-materialscloud` first (matcloud.xyz) and monitored for ~1 week before then being further deployed to production?

**Comment by unkcpz** [comment]
@CasperWA thanks! Do you have any suggestion that we can have a benchmark with some monitor service or from system statistics inside the container to see the improvement?

**Comment by CasperWA** [comment]
> @CasperWA thanks! Do you have any suggestion that we can have a benchmark with some monitor service or from system statistics inside the container to see the improvement?

I think @dou-du has a good handle on monitoring the services and tools running through Voilà, if I remember correctly.

**Comment by CasperWA** [comment]
I will merge this and release to dev-dokku (matcloud.xyz). Can either @dou-du, @eimrek or you @unkcpz then regularly try out and monitor the client on dev-dokku?

**Comment by CasperWA** [comment]
Link: [optimadeclient.matcloud.xyz](https://optimadeclient.matcloud.xyz).

**Comment by CasperWA** [comment]
There does seem to be an issue with getting the query provider widget up though :/

**Comment by CasperWA** [comment]
No, I have this issue locally as well. I've created an issue in the upstream repository: CasperWA/voila-optimade-client#437

**Comment by unkcpz** [comment]
I see, I think this is critical, I will have a look ASAP.

**Pull request merged**
