### PR TITLE
Use new jump host for dev-dokku CD

### LINKED ISSUE #104: dev dokku deploy CI failed
I find all the deploy to dev-dokku CI is failed with the error below, have you encountered this before?  @CasperWA 

https://github.com/materialscloud-org/tools-optimade-client/runs/6107360371?check_suite_focus=true
```
Run git remote add dev-dokku dokku@matcloud.xyz:optimadeclient
  git remote add dev-dokku dokku@matcloud.xyz:optimadeclient
  git config --global user.email "casper.andersen@epfl.ch"
  git config --global user.name "Casper Welzel Andersen"
  git checkout master
  git push dev-dokku master
  shell: /usr/bin/bash -e {0}
Already on 'master'
Your branch is up to date with 'origin/master'.
kex_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Process completed with exit code 1[2](https://github.com/materialscloud-org/tools-optimade-client/runs/6107360371?check_suite_focus=true#step:5:2)[8](https://github.com/materialscloud-org/tools-optimade-client/runs/6107360371?check_suite_focus=true#step:5:8).
```

### PR DESCRIPTION
**Pull request by CasperWA**
Fixes #104 

This implements a new SSH jump host at SINTEF for deploying on dev-dokku.

Temporarily the workflow has been activated for PRs. This will be removed before merging.

### CODE REVIEW

**Comment by CasperWA** [comment]
It works! :) (See [this job run](https://github.com/materialscloud-org/tools-optimade-client/runs/7038871758?check_suite_focus=true)).

**Comment by unkcpz** [comment]
@CasperWA thanks! But I am still confused about why the SINTEF host is involved here? Is that the push happening between GitHub machine and dokku machine?

**Comment by CasperWA** [comment]
Yes. The issue is that the dokku machine has closed for which IP addresses can connect to it. I asked @borellim to open for all the public IP addresses in the SINTEF network, and so I can push to the dokku servers from SINTEF. Hence the jump host to be in SINTEF. But you should have that access as well through EPFL, however, you don't have the proper SSH key for the application. Something you should maybe have. @dou-du might have an SSH key with administrative rights, so you can access the machine anyway, not just this application but all of the applications.

**Comment by unkcpz** [comment]
If I understand correctly, you also go to the setting of the repository and change the old secret? 
In this file https://github.com/materialscloud-org/openstack-ansible/blob/master/group_vars/dokku_servers.yml. You, me and  Leopold can push to the dokku server. Is that what you mean?

**Comment by dou-du** [comment]
> Yes. The issue is that the dokku machine has closed for which IP addresses can connect to it. I asked @borellim to open for all the public IP addresses in the SINTEF network, and so I can push to the dokku servers from SINTEF. Hence the jump host to be in SINTEF. But you should have that access as well through EPFL, however, you don't have the proper SSH key for the application. Something you should maybe have. @dou-du might have an SSH key with administrative rights, so you can access the machine anyway, not just this application but all of the applications.

Hi Casper, I think the IP restriction has already been lifted.

**Comment by CasperWA** [comment]
> > Yes. The issue is that the dokku machine has closed for which IP addresses can connect to it. I asked @borellim to open for all the public IP addresses in the SINTEF network, and so I can push to the dokku servers from SINTEF. Hence the jump host to be in SINTEF. But you should have that access as well through EPFL, however, you don't have the proper SSH key for the application. Something you should maybe have. @dou-du might have an SSH key with administrative rights, so you can access the machine anyway, not just this application but all of the applications.
> 
> Hi Casper, I think the IP restriction has already been lifted.

Well then the many previous workflow runs should have worked, especially the latest ones, and they didn't. So I don't think it is. Or there's some other block in place.

**Comment by unkcpz** [comment]
Hi @CasperWA, I test push to dokku from both my laptop from home without EPFL VPN and also try from a private server if the key is set correctly, I can access dokku and dev-dokku. Could make me the admin of this repo so I can test with my key?

**Comment by ltalirz** [comment]
@unkcpz now has access

**Pull request merged**
